DB_PORT: 27017
OSU_API_KEY: ''
API_PORT: 4008
VERIFY_USER_TOKEN: ''
TEST_MODE: false
ADMIN_PASS: 'asd123'
OSU_OAUTH_ID: null
OSU_OAUTH_SECRET: ''
JWT_SECRET: 'secret'
OSU_OAUTH_REDIRECT: 'http://localhost:4200/api/login-redirect'
