DB_PORT: 27017
OSU_API_KEY: ''
API_PORT: 4008
SOCKET_PORT: 4100
VERIFY_USER_TOKEN: ''
TEST_MODE: false
FAST_FORWARD_MODE: false
ADMIN_PASS: 'asd123'
OSU_OAUTH_ID: null
OSU_OAUTH_SECRET: ''
JWT_SECRET: 'secret'
OSU_OAUTH_REDIRECT: 'http://localhost:4200/api/login-redirect'
PLAYERS_REQUIRED_TO_START: 1
COUNTDOWN_START: 300
REMOVE_AFK_PLAYERS: true
TWITCH_CLIENT_ID: 'asdasd'
TWITCH_SECRET: 'oijoij'
TWITCH_REDIRECT: 'http://localhost:4200/api/twitch-redirect'
TEST_SECRET: 'asd123'
LOG_LEVEL: 'info'
LOG_TO_FILE: false
DISABLE_LOWER_LVL_LOBBIES: true
DISABLE_AUTO_GAME_CREATION: false
DISABLE_MANIA: false
